# https://github.com/vitest-dev/vitest/blob/main/.github/actions/setup-and-cache/action.yml
name: Setup and Install
description: Setup PNPM and Node.js and install dependencies
inputs:
  node-version:
    required: false
    description: Node.js version for setup-node
    default: 20

runs:
  using: composite

  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
